#!/bin/bash -x                                                                                    
#                                                                                                 
# aprs-send-weather.sh                                                                                 
#                                                                                                      
# send an aprs weather packet to aprsis and RF                                                            
#                                                                                                         
# Install requirements (telnet, python, direwolf):                                                                                                                 
#    apt-get install direwolf 
#    apt-get install telnet
#    apt-get install python3                                                                              
#                                                                                                                     
#  (C)2022 Craig Lamparter                                                                                             
#  GPL v2                                                                                                               
#  Modified by KF8ADQ - to replace Weewx with WeatherUnderGround API (weather.py)

# User serviceable parts:
USER="KF8ADQ"
PASS="1234567"                        # https://apps.magicbug.co.uk/passcode/
DIREWOLFHOSTNAME=localhost

# Call Phyton script to get data from Weather Underground
python weather.py

# packet generated by weewx with weewx-aprs extension installed
STRING=`cat aprs.pkt`

# telnet to aprsis server, login, send concatenated string, quit
echo Sending: $STRING
{
sleep 2
echo "user $USER pass $PASS vers aprs-send-weather 0.99"
sleep 2
printf  "$USER>APRS,TCPIP*:$STRING\n"
sleep 5
echo "^]"
echo "quit"
} | telnet noam.aprs2.net 14580
ERR="${PIPESTATUS[0]}"
if [ $ERR -eq 0 ]; then
   echo "Message sent."
else
   echo "ERROR: telnet returned $ERR."
fi


# Now send the packet to a KISS TNC to transmit over RF

echo "Sending packet to Radio TNC."
PACKET="$USER>APRS,WIDE1-1:$STRING"
{
sleep 5    # allow kissutil time to make connection
echo $PACKET
} | kissutil -h $DIREWOLFHOSTNAME




exit $ERR
